name: CI Checks
on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight

jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - run: npm ci
      - run: npm run lint

  test:
    name: Run tests
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - run: npm ci
      - run: npm test

  check-dist:
    name: Check Distribution
    runs-on: ubuntu-22.04
    env:
      BUNDLE_FILE: "dist/index.js"
      BUNDLE_COMMAND: "npm run bundle"
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: 24

      - name: Install
        run: npm ci

      - name: Verify Latest Bundle
        uses: redhat-actions/common/bundle-verifier@a7e9fd367034e38805280ad71d9cc35e2d9f6f9d # v1
        with:
          bundle_file: ${{ env.BUNDLE_FILE }}
          bundle_command: ${{ env.BUNDLE_COMMAND }}

  check-inputs-outputs:
    name: Check Input and Output enums
    runs-on: ubuntu-22.04
    env:
      IO_FILE: ./src/generated/inputs-outputs.ts
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Install dependencies
        run: npm ci

      - name: Verify Input and Output enums
        uses: redhat-actions/common/action-io-generator@a7e9fd367034e38805280ad71d9cc35e2d9f6f9d # v1
        with:
          io_file: ${{ env.IO_FILE }}
